I.addDependency('js/vendor/bgiframe.js', ['bgiframe'], []);
I.addDependency('js/vendor/class.js', ['class'], []);
I.addDependency('js/vendor/dimensions.js', ['dimensions'], []);
I.addDependency('extensions/numerator.js', ['I._Numerator_'], ['I.numerable', 'class']);
I.addDependency('js/site/ra.js', ['TEST.reallyawesome'], []);
I.addDependency('js/vendor/RML.js', ['RML'], []);
I.addDependency('js/vendor/tooltip.js', ['tooltip'], []);
I.addDependency('js/vendor/delegate.js', ['delegate'], []);
I.addDependency('http://code.jquery.com/jquery-1.5.2.min.js', ['jQuery'], []);
I.addDependency('js/site/test.js', ['TEST'], ['jQuery','RML','TEST.reallyawesome']);
I.addDependency('extensions/numerable.js', ['I.numerable'], []);
