__i__.addDependency('js/vendor/bgiframe.js', ['bgiframe'], []);
__i__.setNoCallback(['bgiframe']);
__i__.addDependency('js/tests/reallyAwesomeSpec.js', ['reallyAwesomeSpec'], ['TEST.reallyAwesome']);
__i__.addDependency('js/vendor/dimensions.js', ['dimensions'], []);
__i__.setNoCallback(['dimensions']);
__i__.addDependency('js/tests/testSpec.js', ['testSpec'], ['TEST']);
__i__.addDependency('js/tests/tests.js', ['TESTS'], ['reallyAwesomeSpec', 'testSpec']);
__i__.addDependency('js/vendor/RML.js', ['RML'], []);
__i__.setNoCallback(['RML']);
__i__.addDependency('js/vendor/tooltip.js', ['tooltip'], []);
__i__.setNoCallback(['tooltip']);
__i__.addDependency('js/vendor/delegate.js', ['delegate'], []);
__i__.setNoCallback(['delegate']);
__i__.addDependency('js/site/reallyAwesome.js', ['TEST.reallyAwesome'], []);
__i__.setNoCallback(['TEST.reallyAwesome']);
__i__.addDependency('http://code.jquery.com/jquery-1.5.2.min.js', ['jQuery'], []);
__i__.setNoCallback(['jQuery']);
__i__.addDependency('js/site/test.js', ['TEST'], ['jQuery','RML','TEST.reallyAwesome']);
