I.addDependency('js/vendor/bgiframe.js', ['bgiframe'], [], false, false);
I.addDependency('js/site/ra.js', ['TEST.reallyawesome','TEST.alsoreallyawesome'], [], true, false);
I.addDependency('js/vendor/dimensions.js', ['dimensions'], [], false, false);
I.addDependency('js/site/ra.js', ['TEST.reallyawesome','TEST.alsoreallyawesome'], [], true, false);
I.addDependency('js/vendor/rml.js', ['rml'], [], false, true);
I.addDependency('js/vendor/tooltip.js', ['tooltip'], [], false, false);
I.addDependency('js/vendor/delegate.js', ['delegate'], [], false, false);
I.addDependency('js/site/test.js', ['TEST'], ['rml','jquery','TEST.reallyawesome','TEST.alsoreallyawesome'], false, true);
I.addDependency('http://code.jquery.com/jquery-1.5.2.min.js', ['jquery'], [], true, false);
