var I=I||{};I.addDependency=function(a,b,d){for(var c,a=a.replace(/\\/g,"/"),e=this._dependencies,g=0;c=b[g];g++)e.nameToPath[c]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][c]=!0;for(c=0;b=d[c];c++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0};I._amCached={};
I.amDefined=function(a,b,d){var c;c=0;var e=[],g=this._dependencies;a||(a=this._anonPrefix+this._anonCounter,this._anonCounter++);b=typeof b==="string"?b.split("&"):b;if(typeof d!=="function")throw Error("Missing or incorrect type of callback parameter");for(var f=0,k=b.length;f<k;f++){var h=b[f];if(h in this._amLoaded){var j=g.requires[g.nameToPath[h]];if(j)for(var i in j){if(!(i in this._amLoaded)){c++;break}if(!(i in this.amVendor)&&!this._returnForName[i]){c++;break}}e.push(this._returnForName[h]||
this.getNamespace(h))}else c++}c===0?this._returnForName[a]=d.apply(this.global,e):(c=b.join("&"),a in this._amWaiting||(this._amWaiting[a]={},this._amWaiting[a][c]=d))};I.amIE=navigator.appName.indexOf("Microsoft")===0;I._amLoaded={};I.amVendor={jQuery:!0};I._amWaiting={};I._anonCounter=0;I._anonPrefix="anon_";
I.cache=function(a){if(typeof a!=="string")for(var b;b=a.shift();)this.cache(b);else if(!(a in this._amCached))this.amIE?(new Image).src=this._dependencies.nameToPath[a]:(b=document.createElement("object"),b.data=this._dependencies.nameToPath[a],b.width=0,b.height=0,document.body.appendChild(b)),this._amCached[a]=!0};I._dependencies={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}};I.doc=document;
I._exportNamespace=function(a,b,d){a=a.split(".");d=d||this.global;!(a[0]in d)&&d.execScript&&d.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)!a.length&&b?d[c]=b:d=d[c]?d[c]:d[c]={}};I._getDepsFromPath=function(a){return a in this._dependencies.pathToNames?this._dependencies.pathToNames[a]:null};I.getNamespace=function(a,b){for(var d=a.split("."),c=b||this.global,e;e=d.shift();)if(c[e])c=c[e];else return null;return c};
I._getPathFromDeps=function(a){return a in this._dependencies.nameToPath?this._dependencies.nameToPath[a]:null};I.global=this;I._included={};I._ns={};I.parse=function(){var a,b,d;arguments.length===3&&(a=arguments[2]);a?(b=arguments[1],d=arguments[0]):(a=arguments[1],b=arguments[0],d=!1);if(typeof b!=="string")for(var c=0;c<b.length;c++)this.require(b[c]);else this.require(b);this.amDefined(d,b,a)};
I.provide=function(a,b){if(I.getNamespace(a)&&!I._ns[a])throw Error('Namespace "'+a+'" already declared.');for(var d=a;d=d.substring(0,d.lastIndexOf("."));)this._ns[d]=!0;this._exportNamespace(a,b)};I.require=function(a){if(!(a in this._amLoaded)){var b=this._getPathFromDeps(a);if(b)this._included[b]=!0,this._writeScripts();else throw a="I.require could not find: "+a,this.global.console&&this.global.console.error(a),Error(a);}};I._returnForName={};I._toStr=Object.prototype.toString;
I._waitListener=function(){var a=I._getDepsFromPath(this.getAttribute("src")),b;for(b in a)I._amLoaded[b]=!0;a=I._amWaiting;I._amWaiting={};for(var d in a)if(a.hasOwnProperty(d))for(var c in a[d])I.amDefined(d,c,a[d][c])};
I._writeScripts=function(){function a(e){if(!(e in c.written)){if(!(e in c.visited)&&(c.visited[e]=!0,e in c.requires))for(var f in c.requires[e])if(f in c.nameToPath)a(c.nameToPath[f]);else if(!I.getNamespace(f))throw Error("Undefined nameToPath for "+f);e in d||(d[e]=!0,b.push(e))}}var b=[],d={},c=this._dependencies,e;for(e in this._included)c.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])this._writeScriptTag(b[e]);else throw Error("Undefined dependency");};
I._writeScriptTag=function(a){if(!this._dependencies.written[a]){this._dependencies.written[a]=!0;var b=this.doc.createElement("SCRIPT");b.setAttribute("src",a);I.amIE?b.onreadystatechange=function(){(b.readyState=="loaded"||b.readyState=="complete")&&I._waitListener.call(b)}:b.onload=I._waitListener;this.doc.getElementsByTagName("HEAD")[0].appendChild(b)}};
window.define=function(){var a=Array.prototype.slice.call(arguments),b;I._toStr.call(a[0])==="[object String]"&&(b=a.shift());switch(I._toStr.call(a[0])){case "[object Array]":b?I.provide(b):b=!1;if(a[1]&&typeof a[1]==="function")I.parse(b,a[0],a[1]);else throw Error("Unsupported use of dependencies");break;case "[object Function]":throw Error("Function as first argument unsupported");case "[object Object]":if(!b)b=document.getElementsByTagName("script"),b=b[b.length-1].src;I.provide(b,a[0]);break;
default:throw Error("Unsupported argument type");}};window.define.amd={};__cache__=function(){I.cache.apply(I,arguments)};__parse__=function(){I.parse.apply(I,arguments)};window.require=function(){I.require.apply(I,arguments)};