var I=I||{};I.global=this;I.basePath="";I.doc=document;I.addDependency=function(a,b,c,d,e){var f;a=a.replace(/\\/g,"/");for(var g=this._dependencies,h=0;f=b[h];h++){g.nameToPath[f]=a;a in g.pathToNames||(g.pathToNames[a]={});g.pathToNames[a][f]=true}for(f=0;b=c[f];f++){a in g.requires||(g.requires[a]={});g.requires[a][b]=true}if(d)this._async[a]=true;if(e)this._defer[a]=true};
I.amDefined=function(a,b){var c,d,e=[];c=typeof a==="string"?a.split(">"):a;d=typeof b==="function"?[b]:b;for(var f;f=c.shift();)this._amLoadedChk(f)||e.push(f);if(e.length){c=e.length===1?e[0]:e.join(">");for(this._amWaitingChk(c)||(this._amWaiting[c]=[]);e=d.shift();)this._amWaiting[c].push(e)}else for(;c=d.shift();)c.call(this.global)};I._amWaiting={};I._amWaitingChk=function(a){return a in this._amWaiting};I._amLoaded={};I._amLoadedChk=function(a){return a in this._amLoaded};
I._waitListener=function(){var a=I._getDepsFromPath(this.getAttribute("path")),b;for(b in a)I._amLoaded[b]=true;a=I._amWaiting;I._amWaiting={};for(var c in a)a.hasOwnProperty(c)&&I.amDefined(c,a[c])};I._exportPath=function(a,b,c){a=a.split(".");c=c||this.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b)c[d]=b;else c=c[d]?c[d]:c[d]={}};
I.getObjectByName=function(a,b){for(var c=a.split("."),d=b||this.global,e;e=c.shift();)if(d[e])d=d[e];else return null;return d};I._getPath=function(){if(this.global.BASE_PATH)this.basePath=this.global.BASE_PATH;else for(var a=this.doc.getElementsByTagName("script"),b=a.length-1;b>=0;--b){var c=a[b].src,d=c.length;if(c.substr(d-4)==="i.js"){I.basePath=c.substr(0,d-4);break}}};
I.provide=function(a){if(I.getObjectByName(a)&&!I._ns[a])throw Error('Namespace "'+a+'" already declared.');for(var b=a;b=b.substring(0,b.lastIndexOf("."));)this._ns[b]=true;this._exportPath(a)};I.require=function(a,b,c){if(!I.getObjectByName(a)){var d=this._getPathFromDeps(a);if(d){this._included[d]=true;if(b)this._async[d]=true;if(c)this._defer[d]=true;this._writeScripts()}else{a="I.require could not find: "+a;this.global.console&&this.global.console.error(a);throw Error(a);}}};I._included={};
I._async={};I._defer={};I._dependencies={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}};I._getPathFromDeps=function(a){return a in this._dependencies.nameToPath?this._dependencies.nameToPath[a]:null};I._getDepsFromPath=function(a){return a in this._dependencies.pathToNames?this._dependencies.pathToNames[a]:null};I._ns={};
I._writeScripts=function(){function a(f){if(!(f in d.written)){if(!(f in d.visited)){d.visited[f]=true;if(f in d.requires)for(var g in d.requires[f])if(g in d.nameToPath)a(d.nameToPath[g]);else if(!I.getObjectByName(g))throw Error("Undefined nameToPath for "+g);}if(!(f in c)){c[f]=true;b.push(f)}}}var b=[],c={},d=this._dependencies,e;for(e in this._included)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])this._writeScriptTag({src:this.basePath+b[e],path:b[e],async:this._async[b[e]]||false,defer:this._defer[b[e]]||
false});else throw Error("Undefined script input");};I._writeScriptTag=function(a){if(!this._dependencies.written[a.src]){this._dependencies.written[a.src]=true;var b=this.doc.createElement("SCRIPT");b.src=a.src;b.setAttribute("path",a.path);if(a.async)b.async=true;if(a.defer)b.defer=true;b.onload=I._waitListener;b.onreadystatechange=function(){b.readyState=="complete"&&I._waitListener.call(b)};this.doc.getElementsByTagName("HEAD")[0].appendChild(b)}};I._getPath();

